### ISSUE TITLE
App fails to build after updating to RN@0.31.0

### ISSUE THREAD

**Issue by kcfgl** [decosoftware/deco-ide#141]
Really odd issue popped up after updating npm to RN@0.31.0.  I can no longer build and run the app.  I checked for a Deco update, but I'm up to date (1.1.2).  Rolling back to RN@0.30.0 successfully builds.

I get this error:

 ```
   ../node_modules/react-native/node_modules/commander/index.js:41
    this.required = ~flags.indexOf('<');

    TypeError: Cannot read property 'indexOf' of undefined
    at new Option (/Users/kanecochran/Google Drive/iOS Development/Arriver/ArriverReact/Arriver/node_modules/react-native/node_modules/commander/index.js:41:25)
    at Command.option (../node_modules/react-native/node_modules/commander/index.js:361:16)
    at cliEntry.js:118:25
    at Array.forEach (native)
    at options.forEach (cliEntry.js:118:6)
    at cliEntry.js:134:27
    at Array.forEach (native)
    at Object.run (cliEntry.js:134:12)
    at Object.<anonymous> (../Application Support/com.decosoftware.Deco/libs/Scripts/deco-tool/util/rn-cli.js:29:5)
    at Module._compile (module.js:413:34)
```

And the app fails to build.

**Comment by gdowens** [comment]
Thanks for letting us know. Will be fixed in the next release (we'll default to the latest version of RN in that one).

For now, you can override the default build behavior by creating a configure.deco.js file in your project. Go to "Install > Add deco config to project" in Deco menu. This will create a `configure.deco.js` file in your root directory.

You can see the default config here: https://github.com/decosoftware/deco-ide/blob/master/desktop/deco_unpack_lib/Scripts/deco-tool/configure.deco.js

PROJECT_SETTING specifies constants read from a settings file located at [project_path]/.deco/.settings ...which you can create or open by going into "Deco > Project Settings"

**Comment by kcfgl** [comment]
Thanks for the workaround @gdowens!  Enjoying the IDE, too. You guys are doing some great work.
