### ISSUE TITLE
ERROR  watch null EMFILE

### ISSUE THREAD

**Issue by narekyan** [decosoftware/deco-ide#266]
2016-12-10 15:02 node[53639] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2016-12-10 15:02 node[53639] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2016-12-10 15:02 node[53639] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
{"code":"EMFILE","errno":"EMFILE","syscall":"watch null","filename":null}
 ERROR  watch null EMFILE

See http://facebook.github.io/react-native/docs/troubleshooting.html
for common problems and solutions.
Error: watch null EMFILE
    at exports._errnoException (util.js:856:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1296:21)

**Comment by dchen** [comment]
Thanks for reporting this. We're aware of this occurring in some builds of Deco. Are you using the stable version or the beta version from our website?

**Comment by narekyan** [comment]
Beta version

**Comment by narekyan** [comment]
Another issue with beta

Running with default Deco config
/Applications/Deco.app/Contents/Resources/app/libs/Scripts/deco-tool/util/rn-cli.js:29
cli.run()
   ^

TypeError: Cannot read property 'run' of undefined
    at Object.<anonymous> (/Applications/Deco.app/Contents/Resources/app/libs/Scripts/deco-tool/util/rn-cli.js:29:4)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3

**Comment by mikeconstable** [comment]
I get similar using Deco v1.1.2 (0.7.1)

2016-12-31 16:19 node[58605] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2016-12-31 16:19 node[58605] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2016-12-31 16:19 node[58605] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
 ERROR  watch null EMFILE

See http://facebook.github.io/react-native/docs/troubleshooting.html
for common problems and solutions.
{"code":"EMFILE","errno":"EMFILE","syscall":"watch null","filename":null}
Error: watch null EMFILE
    at exports._errnoException (util.js:856:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1296:21)

**Comment by raul782** [comment]
Hello guys, I bumped into this issue, 0.8.0-beta-1. I'm using macOS Sierra. I have node@6.8.0 + watchman 4.7 installed through brew.
Is there any update how to fix this?

React packager ready.

```
2017-06-04 00:57 node[17927] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-06-04 00:57 node[17927] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-06-04 00:57 node[17927] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-06-04 00:57 node[17927] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-06-04 00:57 node[17927] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
 ERROR  watch null EMFILE
{"code":"EMFILE","errno":"EMFILE","syscall":"watch null","filename":null}
Error: watch null EMFILE
    at exports._errnoException (util.js:856:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1296:21)

See http://facebook.github.io/react-native/docs/troubleshooting.html
for common problems and solutions.
org.reactjs.native.example.Project: 17967
```

**Comment by JeremieDaigle** [comment]
same issue here.

**Comment by spaceemotion** [comment]
Installing watchman 4.9 (via homebrew) did the trick for me (mac osx high sierra)
