### ISSUE TITLE
Packager crashes, unable to talk to watchman

### ISSUE THREAD

**Issue by zenghuilipete** [decosoftware/deco-ide#36]
After i clicked one simulator, red box appeared in simulator which shows "could not connect to development server". Bellow are console error info in packager output:
 ┌────────────────────────────────────────────────────────────────────────────┐ 
 │  Running packager on port 8081.                                            │ 
 │                                                                            │ 
 │  Keep this packager running while developing on any JS projects. Feel      │ 
 │  free to close this tab and run your own packager instance if you          │ 
 │  prefer.                                                                   │ 
 │                                                                            │ 
 │  https://github.com/facebook/react-native                                  │ 
 │                                                                            │ 
 └────────────────────────────────────────────────────────────────────────────┘ 
Looking for JS files in
   /Users/lizenghui/.Deco/tmp/Project 

[11:25:02 AM] <START> Building Dependency Graph
[11:25:02 AM] <START> Crawling File System
[Hot Module Replacement] Server listening on /hot

React packager ready.

2016-05-27T11:25:02,749: [cli] failed to identify PDU: fill_buffer: EOF
2016-05-27T11:25:02,749: [cli] unable to talk to your watchman on /usr/local/var/run/watchman/lizenghui-state/sock! (Undefined error: 0)

/Users/lizenghui/Library/LaunchAgents/com.github.facebook.watchman.plist: service already loaded
2016-05-27T11:25:02,748: [cli] failed to identify PDU: fill_buffer: EOF
2016-05-27T11:25:02,749: [cli] unable to talk to your watchman on /usr/local/var/run/watchman/lizenghui-state/sock! (Undefined error: 0)

Watchman:  watchman--no-pretty get-sockname returned with exit code 1 /Users/lizenghui/Library/LaunchAgents/com.github.facebook.watchman.plist: service already loaded
2016-05-27T11:25:02,748: [cli] failed to identify PDU: fill_buffer: EOF
2016-05-27T11:25:02,749: [cli] unable to talk to your watchman on /usr/local/var/run/watchman/lizenghui-state/sock! (Undefined error: 0)

 ERROR  watchman--no-pretty get-sockname returned with exit code 1 /Users/lizenghui/Library/LaunchAgents/com.github.facebook.watchman.plist: service already loaded
2016-05-27T11:25:02,748: [cli] failed to identify PDU: fill_buffer: EOF
2016-05-27T11:25:02,749: [cli] unable to talk to your watchman on /usr/local/var/run/watchman/lizenghui-state/sock! (Undefined error: 0)

Error: watchman--no-pretty get-sockname returned with exit code 1 /Users/lizenghui/Library/LaunchAgents/com.github.facebook.watchman.plist: service already loaded
2016-05-27T11:25:02,748: [cli] failed to identify PDU: fill_buffer: EOF
2016-05-27T11:25:02,749: [cli] unable to talk to your watchman on /usr/local/var/run/watchman/lizenghui-state/sock! (Undefined error: 0)

    at ChildProcess.<anonymous> (/Users/lizenghui/.Deco/tmp/Project/node_modules/fb-watchman/index.js:198:18)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:827:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:475:12)

See http://facebook.github.io/react-native/docs/troubleshooting.html
for common problems and solutions. 

Anyone come across this kind of situation?

**Comment by dsibiski** [comment]
One solution that worked for me was after you quit Deco, go into Activity Monitor and kill any `watchman` process that is still running.

However, sometimes there is no watchman process there and I found I was still getting this error. However, I use tmux. I found that if I tried to start the packager manually "outside" of tmux (it might take a couple tries), it would end up working. Then trying back "inside" of tmux worked.

Kinda strange, but I was able to reproduce this process reliably.

**Comment by dsibiski** [comment]
I found the "tmux" solution on this issue: https://github.com/facebook/watchman/issues/69

**Comment by chouti** [comment]
Yep, I was able to reproduce the same process, and also it's not possible to kill `watch` in Activity Monitor, as long as I quit the process, it start up automatically.

**Comment by gdowens** [comment]
please reopen a separate issue if the error continues to persist.
