### ISSUE TITLE
Watchman configuration jacked up after installing Deco

### ISSUE THREAD

**Issue by jgo4th** [decosoftware/deco-ide#43]
Previously I was developing with the facebook developed react-native cli tools which used watchman for starting react-native applications. Shortly after installing Deco, I attempted to use these tools to demonstrate previous React-Native Implementations but I keep getting errors similar to this now. 

`Error: watchman--no-pretty get-sockname returned with exit code 1 2016-05-27T09:22:33,591: [cli] failed to identify PDU: fill_buffer: EOF

at ChildProcess.<anonymous> (/Users/josh.goforth/React-Native/Zebreto/node_modules/react-native/node_modules/sane/node_modules/fb-watchman/index.js:198:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)`

Any idea what might have changed in my watchman configuration? I have tried nuking it but to no avail

**Comment by gdowens** [comment]
We are going to change how Deco uses & installs watchman. It's not the best right now. Deco is forcing its own watchman installation. For now, make sure Deco is closed when you want to use your system installed watchman. 

Alternatively, you can remove your system watchman and `export PATH=/usr/local/Deco/watchman:$PATH` to just have everything use Deco's version of watchman.

**Comment by gdowens** [comment]
see #39 and #36
