### ISSUE TITLE
failed to start desktop with 'no such file or directory' error

### ISSUE THREAD

**Issue by younthu** [decosoftware/deco-ide#76]
Hi,

I downloaded source code and tried to build/run it manually by following the instructions in the git page.

while i start the desktop by  "npm run start" in the desktop folder, it failed with following log, i do started "npm run watch" in web folder:

<pre>
➜  desktop git:(release) npm run start

> DecoIDE-Desktop@0.6.0 start /Users/andrewy/sourcecode/github/deco-ide/desktop
> gulp start

[11:02:25] Using gulpfile ~/sourcecode/github/deco-ide/desktop/gulpfile.js
[11:02:25] Starting 'build'...
[11:02:32] [webpack:build] Hash: 3c84b1df3a1382abc5b3
Version: webpack 1.13.1
Time: 6426ms
 Asset     Size  Chunks             Chunk Names
app.js  64.8 kB       0  [emitted]  main
chunk    {0} app.js (main) 227 kB [rendered]
    [0] ./src/main.js 3.25 kB {0} [built]
    [1] external "os" 42 bytes {0} [not cacheable]
    [2] ./src/handlers/index.js 4.63 kB {0} [built]
    [3] external "lodash" 42 bytes {0} [not cacheable]
    [4] ./src/handlers/fileHandler.js 19.3 kB {0} [built]
    [5] external "fs" 42 bytes {0} [not cacheable]
    [6] external "child_process" 42 bytes {0} [not cacheable]
    [7] external "path" 42 bytes {0} [not cacheable]
    [8] external "mkdirp" 42 bytes {0} [not cacheable]
    [9] external "sane" 42 bytes {0} [not cacheable]
   [10] external "fs-plus" 42 bytes {0} [not cacheable]
   [11] ./src/fs/fileSystem.js 7 kB {0} [built]
   [12] external "require('electron')" 42 bytes {0} [not cacheable]
   [13] ./src/log/logger.js 5.04 kB {0} [built]
   [14] external "winston" 42 bytes {0} [not cacheable]
   [15] external "raven" 42 bytes {0} [not cacheable]
   [16] ./src/bridge/index.js 5.41 kB {0} [built]
   [17] external "events" 42 bytes {0} [not cacheable]
   [18] ./src/bridge/requestEmitter.js 3.81 kB {0} [built]
   [19] ../shared/src/constants/ipc/FileConstants.js 6.61 kB {0} [built]
   [20] ../shared/src/constants/ipc/ComponentConstants.js 2.36 kB {0} [built]
   [21] ../shared/src/constants/ipc/ProcessConstants.js 3.94 kB {0} [built]
   [22] ../shared/src/constants/ipc/ProjectConstants.js 3.49 kB {0} [built]
   [23] ../shared/src/constants/ipc/WindowConstants.js 2.5 kB {0} [built]
   [24] ../shared/src/constants/ipc/ModuleConstants.js 2.77 kB {0} [built]
   [25] ../shared/src/constants/ipc/ErrorConstants.js 1.83 kB {0} [built]
   [26] ./src/actions/fileActions.js 4.07 kB {0} [built]
   [27] ./src/actions/genericActions.js 1.73 kB {0} [built]
   [28] ./src/handlers/projectHandler.js 8.02 kB {0} [built]
   [29] ./src/actions/projectActions.js 1.98 kB {0} [built]
   [30] ./src/constants/DecoPaths.js 2.21 kB {0} [built]
   [31] ./src/process/simulatorController.js 5.37 kB {0} [built]
   [32] ./src/fs/model.js 3.06 kB {0} [built]
   [33] ./src/process/utils/simulatorUtils.js 2.34 kB {0} [built]
   [34] ./src/process/packagerController.js 4.74 kB {0} [built]
   [35] ./src/actions/processActions.js 2.11 kB {0} [built]
   [36] ./src/constants/BinaryPaths.js 844 bytes {0} [built]
   [37] ./src/handlers/windowHandler.js 7.04 kB {0} [built]
   [38] ./src/actions/windowActions.js 1.53 kB {0} [built]
   [39] ./src/handlers/processHandler.js 8.67 kB {0} [built]
   [40] ./src/process/utils/xcodeUtils.js 1.97 kB {0} [built]
   [41] ./src/process/utils/findXcodeProject.js 1.52 kB {0} [built]
   [42] ./src/handlers/componentHandler.js 7.27 kB {0} [built]
   [43] ./src/actions/componentActions.js 1.7 kB {0} [built]
   [44] ./src/handlers/moduleHandler.js 17.5 kB {0} [built]
   [45] external "jsonfile" 42 bytes {0} [not cacheable]
   [46] external "node-dir" 42 bytes {0} [not cacheable]
   [47] ./src/process/npmController.js 11.2 kB {0} [built]
   [48] external "once" 42 bytes {0} [not cacheable]
   [49] ./src/actions/uiActions.js 2.01 kB {0} [built]
   [50] ../shared/src/constants/ipc/UIConstants.js 2.82 kB {0} [built]
   [51] ./src/actions/moduleActions.js 2.63 kB {0} [built]
   [52] ./src/window/windowManager.js 6.38 kB {0} [built]
   [53] ./src/constants/DecoDialog.js 2.21 kB {0} [built]
   [54] ./src/handlers/upgradeHandler.js 12.8 kB {0} [built]
   [55] ./src/menu/menuHandler.js 2.12 kB {0} [built]
   [56] ./src/menu/templateBuilder.js 10.2 kB {0} [built]
   [57] ./src/updateManager.js 4.03 kB {0} [built]
   [58] ./src/process/buildController.js 6.23 kB {0} [built]
   [59] ./src/actions/acceleratorActions.js 2.88 kB {0} [built]
   [60] ../shared/src/constants/ipc/AcceleratorConstants.js 4.74 kB {0} [built]
   [61] external "shell" 42 bytes {0} [not cacheable]

WARNING in app.js from UglifyJs
Side effects in initialization of unused variable electronRequire [./src/main.js:45,4]
Side effects in initialization of unused variable registerHandlers [./src/handlers/index.js:36,13]
Side effects in initialization of unused variable SAVE_SUCCESSFUL [./src/handlers/fileHandler.js:67,2]
Side effects in initialization of unused variable SHARE_SAVE_STATUS [./src/handlers/fileHandler.js:68,2]
Side effects in initialization of unused variable _ [./src/fs/fileSystem.js:22,4]
Side effects in initialization of unused variable fsPlus [./src/fs/fileSystem.js:23,4]
Side effects in initialization of unused variable ipc [./src/bridge/requestEmitter.js:19,6]
Side effects in initialization of unused variable CREATE_DIRECTORY [./src/actions/fileActions.js:29,2]
Side effects in initialization of unused variable confirmSave [./src/actions/fileActions.js:38,13]
Side effects in initialization of unused variable onExternalFileData [./src/actions/fileActions.js:45,13]
Side effects in initialization of unused variable onFileCreated [./src/actions/fileActions.js:54,13]
Side effects in initialization of unused variable onRename [./src/actions/fileActions.js:64,13]
Side effects in initialization of unused variable onFileData [./src/actions/fileActions.js:73,13]
Side effects in initialization of unused variable onFileMetadata [./src/actions/fileActions.js:82,13]
Side effects in initialization of unused variable addSubPath [./src/actions/fileActions.js:91,13]
Side effects in initialization of unused variable addSubPathBatch [./src/actions/fileActions.js:101,13]
Side effects in initialization of unused variable removeSubPath [./src/actions/fileActions.js:108,13]
Side effects in initialization of unused variable removeSubPathBatch [./src/actions/fileActions.js:117,13]
Side effects in initialization of unused variable Logger [./src/actions/genericActions.js:18,6]
Side effects in initialization of unused variable onError [./src/actions/genericActions.js:23,13]
Side effects in initialization of unused variable onSuccess [./src/actions/genericActions.js:34,13]
Side effects in initialization of unused variable path [./src/actions/projectActions.js:20,6]
Dropping unused variable EventTypes [./src/actions/projectActions.js:30,6]
Dropping unused variable RequestTypes [./src/actions/projectActions.js:34,6]
Side effects in initialization of unused variable setProject [./src/actions/projectActions.js:37,13]
Side effects in initialization of unused variable newProject [./src/actions/projectActions.js:45,13]
Side effects in initialization of unused variable save [./src/actions/projectActions.js:51,13]
Side effects in initialization of unused variable saveAs [./src/actions/projectActions.js:57,13]
Side effects in initialization of unused variable Logger [./src/constants/DecoPaths.js:23,6]
Side effects in initialization of unused variable APP_WATCHER_FILE [./src/process/simulatorController.js:25,6]
Side effects in initialization of unused variable _electron [./src/process/packagerController.js:28,0]
Side effects in initialization of unused variable onPackagerOutput [./src/actions/processActions.js:23,13]
Side effects in initialization of unused variable onPackagerError [./src/actions/processActions.js:30,13]
Side effects in initialization of unused variable listAvailableSims [./src/actions/processActions.js:37,13]
Side effects in initialization of unused variable updateSimulatorStatus [./src/actions/processActions.js:44,13]
Side effects in initialization of unused variable child [./src/handlers/windowHandler.js:105,12]
Side effects in initialization of unused variable Logger [./src/actions/windowActions.js:20,6]
Side effects in initialization of unused variable openProjectDialog [./src/actions/windowActions.js:28,13]
Side effects in initialization of unused variable saveAsDialog [./src/actions/windowActions.js:35,13]
Side effects in initialization of unused variable ERROR [./src/handlers/componentHandler.js:34,8]
Side effects in initialization of unused variable onComponentList [./src/actions/componentActions.js:28,13]
Side effects in initialization of unused variable onImportComponent [./src/actions/componentActions.js:35,13]
Side effects in initialization of unused variable startProgressBar [./src/actions/uiActions.js:20,13]
Side effects in initialization of unused variable updateProgressBar [./src/actions/uiActions.js:30,13]
Side effects in initialization of unused variable endProgressBar [./src/actions/uiActions.js:40,13]
Side effects in initialization of unused variable upgradeStatus [./src/actions/uiActions.js:51,13]
Side effects in initialization of unused variable foundRegistries [./src/actions/moduleActions.js:21,13]
Side effects in initialization of unused variable fs [./src/window/windowManager.js:20,4]
Side effects in initialization of unused variable nativeImage [./src/window/windowManager.js:25,4]
Side effects in initialization of unused variable app [./src/window/windowManager.js:26,4]
Side effects in initialization of unused variable Logger [./src/window/windowManager.js:28,4]
Side effects in initialization of unused variable INFO [./src/constants/DecoDialog.js:23,13]
Side effects in initialization of unused variable QUESTION [./src/constants/DecoDialog.js:33,13]
Side effects in initialization of unused variable Logger [./src/updateManager.js:27,6]
Side effects in initialization of unused variable Logger [./src/actions/acceleratorActions.js:18,6]
Side effects in initialization of unused variable shouldCreateProject [./src/actions/acceleratorActions.js:31,13]
Side effects in initialization of unused variable shouldSaveProject [./src/actions/acceleratorActions.js:37,13]
Side effects in initialization of unused variable shouldSaveProjectAs [./src/actions/acceleratorActions.js:43,13]
Side effects in initialization of unused variable openProjectDialog [./src/actions/acceleratorActions.js:49,13]
Side effects in initialization of unused variable toggleTerm [./src/actions/acceleratorActions.js:55,13]
Side effects in initialization of unused variable openInstallModuleDialog [./src/actions/acceleratorActions.js:61,13]
Side effects in initialization of unused variable openImportTemplateDialog [./src/actions/acceleratorActions.js:67,13]
[11:02:32] Finished 'build' after 6.46 s
[11:02:32] Starting 'start'...
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/andrewy/sourcecode/github/deco-ide/desktop/node_modules/electron-prebuilt/path.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.<anonymous> (/Users/andrewy/sourcecode/github/deco-ide/desktop/node_modules/electron-prebuilt/index.js:4:42)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
</pre>

Can anyone help on this?

**Comment by dchen** [comment]
@younthu Can you try running npm install one more time in the desktop directory? Also check your version of node and npm, run node -v and npm -v

**Comment by younthu** [comment]
@dchen , i tried your instructions,and failed to start run,  below is the log, the "npm start run" log is the same as before, so, i omitted that part.

<pre>
➜  desktop git:(release) ✗ npm install
npm WARN DecoIDE-Desktop@0.6.0 No repository field.
npm WARN DecoIDE-Desktop@0.6.0 No license field.
➜  desktop git:(release) ✗ node -v
v5.9.0
➜  desktop git:(release) ✗ npm -v
3.7.3
➜  desktop git:(release) ✗
</pre>

**Comment by gdowens** [comment]
`rm -rf desktop/node_modules` and then `npm install` in the desktop directory. Looks like there's a problem with your electron-prebuilt node module. Not sure why.

**Comment by younthu** [comment]
@gdowens , i tried your suggestion, it works now! 

many thanks!

**Comment by gdowens** [comment]
🙇
