### ISSUE TITLE
"Cannot find module './cli'" when launching simulator

### ISSUE THREAD

**Issue by zaach** [decosoftware/deco-ide#91]
After installing deco for the first time today and creating a new project, I see this error in the console after launching the simulator:

```
[15:45:18] Finished 'build' after 4.72 s
[15:45:18] Starting 'start'...
info: Deco initializing...
info: No user specified config file was found, falling back to default!

error: packager stderr module.js:341
    throw err;
    ^

Error: Cannot find module './cli'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/zcarter/.Deco/tmp/Project/node_modules/.bin/react-native:24:3)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)

info: No user specified config file was found, falling back to default!

info: org.reactjs.native.example.Project: 28754

parent has disconnected, process will shut down
```

along with the red "cannot connect to dev server" error screen for the app.

**Comment by gdowens** [comment]
Hey @zaach looks like something is wrong with the node_modules... 

Two questions...
1. Closing Deco and starting a new project does not fix it, right? 
2. What happens when you open an existing React Native project? Say, a project made using `react-native init`?

**Comment by zaach** [comment]
1. Nope
2. I get a different error. Looks like it can't find the simulator:

```

error:  Error: ENOENT: no such file or directory, stat '/Users/zcarter/venndev/testide/ios/build/Build/Products/Debug-iphonesimulator'
    at Error (native)
    at fs.statSync (fs.js:986:18)
    at Object.fs.statSync (ELECTRON_ASAR.js:263:16)
    at e.o.value (/Users/zcarter/venndev/deco-ide/desktop/build/app.js:2:6887)
    at e.o.value (/Users/zcarter/venndev/deco-ide/desktop/build/app.js:2:7629)
    at emitThree (events.js:116:13)
    at t.emit (events.js:194:7)
    at t.<anonymous> (/Users/zcarter/venndev/deco-ide/desktop/build/app.js:1:16365)
    at emitThree (events.js:116:13)
    at t.emit (events.js:194:7)
    at t.i.value (/Users/zcarter/venndev/deco-ide/desktop/build/app.js:1:18054)
    at EventEmitter.<anonymous> (/Users/zcarter/venndev/deco-ide/desktop/build/app.js:1:18148)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at EventEmitter.<anonymous> (/Users/zcarter/venndev/deco-ide/desktop/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:128:18)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
info: No user specified config file was found, falling back to default!
```

**Comment by zaach** [comment]
Well now, the original case *is* working now. I tried it twice yesterday and had no luck, but today after trying the 2nd case I gave it a go and it works. 2nd case still repeatedly failing.
